# SPDX-FileCopyrightText: © 2023 Olivier Meunier <olivier@neokraft.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

all: clean build

build:
	go run ../../tools/docs src assets

clean:
	rm -rf assets/*
