# SPDX-FileCopyrightText: © 2023 Olivier Meunier <olivier@neokraft.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

# Extract all the messages
extract:
	python3 messages.py extract

# Update a given locale messages
update:
	python3 messages.py update
