# SPDX-FileCopyrightText: 2025 mohamed hamdi <haamdi@outlook.com>
#
# SPDX-License-Identifier: ISC

# .github/workflows/build.yml
name: Build on PR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install tools with Mise
        uses: jdx/mise-action@v2
        with:
          install: true   # runs `mise install` using your mise.toml
          cache: true     # caches Mise & tool shims for speed

      - name: Bootstrap Go & Web dependencies
        run: |
          make setup            # downloads Go modules and node packages

      - name: Compile frontend & server
        run: |
          make all              # generate + build server (dist/readeck)
