#!/usr/bin/make

# SPDX-FileCopyrightText: © 2021 Olivier Meunier <olivier@neokraft.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

.PHONY:build
build:
	npm run build

.PHONY:clean
clean:
	npm run clean

.PHONY:lint
lint:
	npm run lint

.PHONY:watch
watch:
	npm run watch
